# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ldflags:
      - -s -w -X weather-cli/cmd.Version={{.Version}}
    main: ./main.go
    binary: weather-cli

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

brews:
  - repository:
      owner: cybo42
      name: tap-fork
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        base:
          owner: cybo42
          name: demo-homebrew-tap
          branch: main
  - name: weather-cli
    homepage: "https://github.com/cybo42/weather-cli"
    description: "A simple CLI application that prints hello world"
    license: "MIT"
    tap:
      owner: cybo42
      name: demo-homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    folder: Formula
    install: |
      bin.install "weather-cli"
    test: |
      system "#{bin}/weather-cli --version"

nfpms:
  - 
    id: packages
    package_name: weather-cli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: cybo42
    homepage: https://github.com/cybo42/weather-cli
    maintainer: cybo42 <cybo42@example.com>
    description: A simple CLI application for weather information
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    
    # Dependencies and recommendations for the package
    dependencies:
      - git
    
    # Version schema
    version_metadata: git
    
    # RPM specific
    rpm:
      group: Applications/System
    
    # DEB specific
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

# The lines beneath this are called `modelines`. See `:help modeline`
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj